### ISSUE TITLE
Possible for consumer to seek to a given offset in the topic?

### ISSUE THREAD

**Issue by varunpatro** [mfontanini/cppkafka#1]
Something like this in the Java API:

https://kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#seek(org.apache.kafka.common.TopicPartition,%20long)

and in librdkafka:

https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.c#L1735

**Comment by mfontanini** [comment]
That function is listed in the "legacy consumer" part of librdkafka's code. Do you know if it works with the high level consumer in librdkafka?

Otherwise, you can always use `Consumer::assign` passing the offsets for every partition.

**Comment by varunpatro** [comment]
Sorry, I'm not sure if that works in the high level consumer.

I did try using `Consumer::assign` but it fails.

Here's what I did:

```
auto tp = TopicPartition("test", 0);
tp.set_offset(TopicPartition::OFFSET_END);

cout << tp.get_partition() << tp.get_offset() << endl; // this gives me 0 and -1

consumer.assign({tp});

auto tpl = consumer.get_assignment();
auto offset = consumer.get_offsets(tpl[0]);
count << get<0>(offset) << std<1>(offset) << endl; // this gives me -1001 and -1001
```

Questions:

1. I need to get the latest position of a message in a given topic. How do I do this?
2. I need to seek to a given position in a topic. How do I do this?

**Comment by mfontanini** [comment]
Can't you just subscribe to the topic and use `auto.offset.reset` to `latest`? Using assign with a specific offset should work, there's nothing that `cppkafka` is doing besides forwarding that call to `librdkafka`.

Also, what do you mean "it fails"?

**Comment by mfontanini** [comment]
I've used this on some application I wrote and it works as expected. Did you manage to make it work? Just assign and you'll start getting messages for that offset.

**Comment by mfontanini** [comment]
Closing as this works as expected. If you couldn't make it work, please re-open.

**Comment by EvilBeaver** [comment]
Same issue.

```c++
cppkafka::TopicPartitionList assignments;
offset = TopicPartition::OFFSET_END;
assignments.push_back({topicName, partition, offset});
consumer->assign(assignments);

cout << consumer->get_offsets(consumer->c->get_assignment()[0]);
```

always gives an INVALID_OFFSET. And consumer doesn't consume anything.

**Comment by EvilBeaver** [comment]
Of course I'm producing on this topic/partition. And bundled kafka console-consumer can read messages. My consumer can't

**Comment by mfontanini** [comment]
I've just tried this locally using rdkafka v0.11.4 and it works as expected. I do get INVALID_OFFSET after querying right after calling `assign` but then I get messages and if I query for the offsets again after I get a message, the query does return the (high) offset correctly.

Are you using the latest version of rdkafka? Again, cppkafka is a super thin layer on top of rdkafka so odds are if there's actually an issue, it's on rdkafka's side and you should create a ticket on their repo.

**Comment by shurazs** [comment]
As far as I could understand, there is a recommendation to use function `assign ` instead of `seek`.
But `assign` is quite heavy because are new|delete in its realization.
Is it possible to implement `seek ` function?

**Comment by filimonov** [comment]
https://github.com/edenhill/librdkafka/issues/1925
