### ISSUE TITLE
How to resolve link issue for example project in mac

### ISSUE THREAD

**Issue by xueyouchao** [mfontanini/cppkafka#102]
I can successfully create libcppkafka.a on mac. But failed to build producer example.
It tries to link librt which I believe not exist on Mac. How can I resolve this link issue?

make producer
Scanning dependencies of target cppkafka
[  4%] Building CXX object src/CMakeFiles/cppkafka.dir/configuration.cpp.o
[  8%] Building CXX object src/CMakeFiles/cppkafka.dir/topic_configuration.cpp.o
[ 12%] Building CXX object src/CMakeFiles/cppkafka.dir/exceptions.cpp.o
[ 16%] Building CXX object src/CMakeFiles/cppkafka.dir/topic.cpp.o
[ 20%] Building CXX object src/CMakeFiles/cppkafka.dir/buffer.cpp.o
[ 25%] Building CXX object src/CMakeFiles/cppkafka.dir/queue.cpp.o
[ 29%] Building CXX object src/CMakeFiles/cppkafka.dir/message.cpp.o
[ 33%] Building CXX object src/CMakeFiles/cppkafka.dir/message_internal.cpp.o
[ 37%] Building CXX object src/CMakeFiles/cppkafka.dir/topic_partition.cpp.o
[ 41%] Building CXX object src/CMakeFiles/cppkafka.dir/topic_partition_list.cpp.o
[ 45%] Building CXX object src/CMakeFiles/cppkafka.dir/metadata.cpp.o
[ 50%] Building CXX object src/CMakeFiles/cppkafka.dir/group_information.cpp.o
[ 54%] Building CXX object src/CMakeFiles/cppkafka.dir/error.cpp.o
[ 58%] Building CXX object src/CMakeFiles/cppkafka.dir/kafka_handle_base.cpp.o
[ 62%] Building CXX object src/CMakeFiles/cppkafka.dir/producer.cpp.o
[ 66%] Building CXX object src/CMakeFiles/cppkafka.dir/consumer.cpp.o
[ 70%] Building CXX object src/CMakeFiles/cppkafka.dir/utils/backoff_performer.cpp.o
[ 75%] Building CXX object src/CMakeFiles/cppkafka.dir/utils/backoff_committer.cpp.o
[ 79%] Building CXX object src/CMakeFiles/cppkafka.dir/utils/poll_strategy_base.cpp.o
[ 83%] Building CXX object src/CMakeFiles/cppkafka.dir/utils/roundrobin_poll_strategy.cpp.o
[ 87%] Linking CXX static library ../lib/libcppkafka.a
[ 91%] Built target cppkafka
Scanning dependencies of target producer
[ 95%] Building CXX object examples/CMakeFiles/producer.dir/producer_example.cpp.o
[100%] Linking CXX executable producer
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [examples/producer] Error 1
make[2]: *** [examples/CMakeFiles/producer.dir/all] Error 2
make[1]: *** [examples/CMakeFiles/producer.dir/rule] Error 2
make: *** [producer] Error 2

**Comment by mfontanini** [comment]
Can you try removing "rt" from [this list](https://github.com/mfontanini/cppkafka/blob/master/examples/CMakeLists.txt#L1) and see if that builds?

**Comment by xueyouchao** [comment]
Yes, it works, for Mac, this library needs to be removed.
