### ISSUE TITLE
Support for Message Headers

### ISSUE THREAD

**Issue by rriggs** [mfontanini/cppkafka#114]
librdkafka added support to the C API for message headers in release 0.11.4.

Any chance of adding message header support to MessageBuilder in the near future?

**Comment by mfontanini** [comment]
I wanted to add support for headers but I never really sat down and implemented that. I'm currently working on other stuff so I won't be able to write this in a while, but we should definitely add support at some point.

**Comment by accelerated** [comment]
I could take a look. Actually in my cppkafka wrapper we added support for headers inside the packet itself as it was a requirement. The header has a small shim with a version number a a header length which points to the beginning of the serialized message. Anything between the shim and the message is the header so it can be extracted separately, so I will see if it make sense to modify our code and this one.  I am also trying to see if we can open source it so it could be maintained more easily going forward.

**Comment by accelerated** [comment]
Ok so I'll work on this, starting next week probably. I think it makes sense to fully support it. I'll issue a design review before coding it so that @mfontanini can approve the overall concept.

**Comment by mfontanini** [comment]
Yeah, this definitely should be supported if someone can put the manpower into building it. I had some thoughts about it when I was considering implementing it but they all faded away by now. Thanks for taking the initiative on this one!

**Comment by accelerated** [comment]
Sure!

**Comment by accelerated** [comment]
Guess we can close this issue now?

**Comment by mfontanini** [comment]
Yep, definitely. This is closed by #115. Btw if you write "fixes #114" in the PR comments I think after the merge related issue gets closed automatically.
