### ISSUE TITLE
Support for allocators

### ISSUE THREAD

**Issue by accelerated** [mfontanini/cppkafka#117]
Hi, Would you accept changes to the BufferedProducer allowing allocators to be passed in for the message buffer (there will be a 2nd default template parameter `Allocator = std::allocator<T>`) and also an overload for the consumers when polling a batch of messages (i.e. so the returned vector of messages can be allocated from an allocator)?

**Comment by mfontanini** [comment]
>  an overload for the consumers when polling a batch of messages

Sounds good, although maybe I'd just modify the existing one and make it take `Allocator = std::allocator<T>`?

> BufferedProducer allowing allocators to be passed in for the message buffer

Do you mean an allocator for the `BufferType` template parameter? Is that really needed? I presume if you want something other than a `cppkafka::Buffer` in there, you'll use something like a `std::vector` and you can provide your own allocator when instantiating the buffered producer (e.g. `BufferedProducer<std::vector<uint8_t, MyAllocator>>`)

**Comment by accelerated** [comment]
For the `BufferedProducer<BufferType>` it would be:
```c++
template <typename BufferType, 
          typename Allocator = std::allocator<ConcreteMessageBuilder<BufferType>>>
class BufferedProducer; 
```
This will not break API/ABI since it's a template and has a default parameter. 

For the `Consumer` we cannot change 
```c++
template <typename Allocator = std::allocator<MessageList>>
using MessageList = std::vector<Message, Allocator>; //breaks abi
```

but maybe we can 
```c++
using MessageList = std::vector<Message>; //uses std::allocator<Message>
template <typename Allocator>
using MessageListWithAlloc = std::vector<Message, Allocator>; //use this in overloaded poll_batch() 

template <typename Allocator>
MessageListWithAlloc<Allocator> poll_batch(size_t max_batch_size, const Allocator& alloc); 
```

something like this ?

**Comment by mfontanini** [comment]
Fair enough, I didn't think about having to pass the allocator in. I kind of regret creating the `MessageList` type alias as it's not really needed and there's no reason to have it. I'm not sure about introducing a `MessageListWithAlloc`, maybe it could just be the following?

```c++
template <typename Allocator>
std::vector<Message, Allocator> poll_batch(size_t max_batch_size, const Allocator& alloc);
```

Regarding the buffered producer, yep, that makes sense too.

**Comment by accelerated** [comment]
Ok will flesh something out after I wrap up the header stuff.
