### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Salem-Guezguez** [mfontanini/cppkafka#121]
I can't compile the code example that creates a producer. (System is ubuntu 16:04)
I get this Error : fatal error: cppkafka/cppkafka.h: No such file or directory
I have created a test directory that contains four directories :  bin, res, src and build . 
I have copied the cppkafka.so in my res directory 
My CMakeList.txt looks like this : 
`cmake_minimum_required(VERSION 2.6)
project(test)
link_directories(${CMAKE_SOURCE_DIR}/res)
find_library(RDKAFKA_LIB rdkafka)
include_directories(SYSTEM ${RDKAFKA_INCLUDE_DIR})

add_executable(mytest src/main.cpp)
target_link_libraries(mytest cppkafka ${RDKAFKA_LIB})`

**Comment by Salem-Guezguez** [comment]
when i do cmake .. i get this message 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/salem/test/build
then make i get the error:
[ 50%] Building CXX object CMakeFiles/mytest.dir/src/main.cpp.o
/home/salem/test/src/main.cpp:1:31: fatal error: cppkafka/cppkafka.h: No such file or directory
compilation terminated.
CMakeFiles/mytest.dir/build.make:62: recipe for target 'CMakeFiles/mytest.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/mytest.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mytest.dir/all' failed
make[1]: *** [CMakeFiles/mytest.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by accelerated** [comment]
I was referring to running cmake on the cppkafka code itself, not on your code. In any case, cppkafka.h is also checked-in so if you checked it out, there's probably an include path issue you have. In the cmake code you pasted above I don't see an include directive for the cppkafka folder.

**Comment by Salem-Guezguez** [comment]
Thanks. It works
