### ISSUE TITLE
Creating Message from ConcreteMessageBuilder

### ISSUE THREAD

**Issue by tgaldes** [mfontanini/cppkafka#137]
Is there a way to use the concrete message builder class to build messages for the Producer to use? The only produce() arguments in producer.h that I see are r/l references to either Messages, or MessageBuilders. I also don't see any functions that return an instance of Message except the one that uses an rd_kafka_message_t* (in message.h:85) as an argument, but if I need to create that myself it seems to make the concrete message builder obsolete, so I know that I'm missing something. An help is much appreciated!

**Comment by mfontanini** [comment]
`BasicMessageBuilder`s can be constructed from `BasicMessageBuilder`s instantiated with different template types. So you should be able to use a, say, `ConcreteMessageBuilder<string>` and pass it along to the `produce(const MessageBuilder&)` overload, which will implicitly construct a `MessageBuilder` from it. 

Regarding the `Message` question, you can't get a `rd_kafka_message` our of a message builder because that's created by rdkafka under the hood. There's no way for a user to create those handles. What's the reason why you need a message handle when producing?

**Comment by tgaldes** [comment]
Thanks for getting back to me!

I don't need a message handle when producing, that's just the only way I saw in the api to construct a message, but using anything from rd_kafka seemed like improper use of the cppkafka api.

For ConcreteMessageBuilder<T>, I don't see how it can be implicitly converted to a MessageBuilder when T != string. ConcreteMessageBuilder and MessageBuilder inherit from BasicMessageBuilder, but Concrete doesn't inherit from MessageBuilder. The example you gave works fine since Concrete<string> is the same type as MessageBuilder, but again, I don't see how to use produce() when T != string

**Comment by tgaldes** [comment]
From what little experience I have with templates it seems like you would need a templated overload of produce():

template <typename T>
void produce(const ConcreteMessageBuilder<T>& builder);

**Comment by mfontanini** [comment]
This should work as it is. It works because of [this](https://github.com/mfontanini/cppkafka/blob/master/include/cppkafka/message_builder.h#L72) constructor. Did you actually try doing this?

**Comment by mfontanini** [comment]
You can't really use doubles. How do you encode doubles on the wire? The idea (and this should probably be stated in the API) is that you provide some type of buffer that holds the data (e.g. `vector`, `string`, etc). cppkafka (and librdkafka) don't know how you want to encode double, your code should handle the conversion and your `ConcreteMessageBuilder` should hold some type of buffer.

**Comment by tgaldes** [comment]
Ah gotcha! Thank you for the clarification of sending over the wire- now understand why there's the limitation. I got it to work with vector<unsigned character>

**Comment by tgaldes** [comment]
Does your api support using non stl containers like char[]/void* and a size to construct payloads?

**Comment by mfontanini** [comment]
I don't think that will work. There should be another overload like [this one](https://github.com/mfontanini/cppkafka/blob/master/include/cppkafka/buffer.h#L97) for `std::array` so at least you can construct them from an array which won't incur a memory allocation. Feel free to add a PR there if you have the time to do so.

**Comment by tgaldes** [comment]
https://github.com/mfontanini/cppkafka/pull/138
