### ISSUE TITLE
relative time as timestamp

### ISSUE THREAD

**Issue by arvidn** [mfontanini/cppkafka#15]
The message timestamp is expressed as a relative time duration (``std::chrono::milliseconds``) [here](https://github.com/mfontanini/cppkafka/blob/master/include/cppkafka/message.h#L195).

That seems like the wrong type, it really should be a ``time_point``, right?

**Comment by mfontanini** [comment]
The timestamp is expressed as a relative time since epoch. So it's arguably the wrong type but not necessarily.

**Comment by rriggs** [comment]
So, we expect everyone to write:

`.timestamp(duration_cast<milliseconds>(system_clock::now() - system_clock::from_time_t(0)))`

Whenever they need a timestamp?  That seems less than ideal.

**Comment by accelerated** [comment]
`.timestamp(duration_cast<milliseconds>(std::chrono::system_clock::now().time_since_epoch()))` should do.

**Comment by accelerated** [comment]
> `.timestamp(duration_cast<milliseconds>(std::chrono::system_clock::now().time_since_epoch()))` should do.

But I agree that `.timestamp(std::chrono::system_clock::now())` would be more user-friendly. I wonder if @mfontanini is ok with adding an overload to this function taking a `time_point`?

**Comment by mfontanini** [comment]
Yeah that should work.

**Comment by mfontanini** [comment]
Also, note that you don't have to specify anything if you want _now_ to be the timestamp in the message. Messages will have now as the timestamp by default so you should only specify one if you want to override it (e.g. you want the timestamp to be something that comes out of the message's contents or something like that).

**Comment by accelerated** [comment]
> Yeah that should work.

@mfontanini, You mean adding the overload or the code snipped I posted?

**Comment by mfontanini** [comment]
Yep, I was referring to that comment.

**Comment by mfontanini** [comment]
Sorry, I meant your code snippet :)

**Comment by mfontanini** [comment]
I mean, adding the overload. Sorry, for the spam!

**Comment by accelerated** [comment]
See [PR#128](https://github.com/mfontanini/cppkafka/pull/128).
