### ISSUE TITLE
%3|1547198932.757|FAIL|rdkafka#producer-1| [thrd:localhost:9092/0]: localhost:9092/0: Connect to ipv6#[::1]:9092 failed: Connection refused (after 0ms in state CONNECT)

### ISSUE THREAD

**Issue by marcoippolito** [mfontanini/cppkafka#155]
Hi @mfontanini .
I just resumed Kafka and cppkafka. And this time I want to get deep knowledge and understanding of both.

After starting Kafka Server, starting 3 brokers (I do follow "Kafka in action" book instructions as starter)

    marco@pc01:~/kafka_2.11-2.0.0$ bin/kafka-topics.sh --zookeeper localhost:2181 --list
    __consumer_offsets
    helloworld
    my-replicated-topic
    my_topic

I activated a producer and a consumer through the CLI:

    marco@pc01:~/kafka_2.11-2.0.0$ bin/kafka-console-producer.sh --broker-list localhost:9092 --topic   
    helloworld
    >Hello! I'm the producer
    >

    marco@pc01:~/kafka_2.11-2.0.0$ bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 
    --topic helloworld
    Hello! I'm the producer

    server0.properties : 
    broker.id=0
    listeners=PLAINTEXT://localhost:9092

Now... I want to execute the simple example, which I've put in the same directory of kafka:

    /home/marco/kafka_2.11-2.0.0

    #include <cppkafka/cppkafka.h>

    using namespace std;
    using namespace cppkafka;

    int main() {
      // Create the config
      Configuration config = {
        { "metadata.broker.list", "127.0.0.1:9092" }
      };
      // Create the producer
      Producer producer(config);
      // Produce a message!
      string message = "hey there!";
      producer.produce(MessageBuilder("my_topic").partition(0).payload(message));
      producer.flush();
      return 0;
    }

The compilation seems fine... but the output says:

    marco@pc01:~/kafka_2.11-2.0.0$ g++ -std=c++17 -lrdkafka -lpthread -lz -lstdc++ plain.cpp  
    -lboost_program_options -lcppkafka -oplain
    marco@pc01:~/kafka_2.11-2.0.0$ ./plain
    %3|1547198932.757|FAIL|rdkafka#producer-1| [thrd:localhost:9092/0]: localhost:9092/0: Connect to 
    ipv6#[::1]:9092 failed: Connection refused (after 0ms in state CONNECT)
    %3|1547198932.757|ERROR|rdkafka#producer-1| [thrd:localhost:9092/0]: localhost:9092/0: Connect to
     ipv6#[::1]:9092 failed: Connection refused (after 0ms in state CONNECT)
    terminate called after throwing an instance of 'cppkafka::HandleException'
      what():  Local: Timed out
    Aborted (core dumped)

What do I have to do to solve the problem?
Looking forward to your kind help.
Marco

**Comment by marcoippolito** [comment]
I seems working now (after rebooting)... I do not really understand what could influence the correct execution of that simple file... Anyway... I will keep trying more stuff, in order to understand it better.

**Comment by anas-gif** [comment]
Hi, I have the same problem, can you help me PLZ

root@07be421e8516:/opt/workspace# kafkacat -P -t places -l 2022_place_canvas_history-000000000000.csv -b kafka1:9092
%3|1668457398.670|FAIL|rdkafka#producer-1| [thrd:kafka1:9092/bootstrap]: kafka1:9092/bootstrap: Failed to resolve 'kafka1:9092': Temporary failure in name resolution (after 10008ms in state CONNECT)
% ERROR: Local: Host resolution failure: kafka1:9092/bootstrap: Failed to resolve 'kafka1:9092': Temporary failure in name resolution (after 10008ms in state CONNECT)
% ERROR: Local: All broker connections are down: 1/1 brokers are down : terminating
