### ISSUE TITLE
Can you create a release with header support please?

### ISSUE THREAD

**Issue by lordpixel23** [mfontanini/cppkafka#160]
Hi,

Header support is a really cool addition. Can you please give me an idea when a 0.3 release with headers may be released? Are things stable enough for a release right now?

Thanks

**Comment by mfontanini** [comment]
Will do but this will have to wait a couple of days. On Tuesday night I may have some time to tag a release. There's also been some recent changes that hopefully won't cause any issues.

**Comment by lordpixel23** [comment]
Thanks very much. That'll be great

**Comment by mfontanini** [comment]
Sorry, I had a busy week and only now managed to sit down to do this. [Here](https://github.com/mfontanini/cppkafka/releases/tag/v0.3.0)'s the new tag.

**Comment by lordpixel23** [comment]
Thank you most kindly

**Comment by guli333** [comment]
hey everyone!
I`m not getting how to send a message headers? Could you provide a code snippet?

Thank you~
