### ISSUE TITLE
rdkafka v0.11.6 doesn't provide rd_kafka_message_status

### ISSUE THREAD

**Issue by abyss7** [mfontanini/cppkafka#161]
There is a section in the code https://github.com/mfontanini/cppkafka/blob/master/include/cppkafka/message.h#L204-L212 :

    #if (RD_KAFKA_VERSION >= RD_KAFKA_MESSAGE_STATUS_SUPPORT_VERSION)
        /**
         * \brief Gets the message persistence status
         */
        rd_kafka_msg_status_t get_status() const {
            assert(handle_);
            return rd_kafka_message_status(handle_.get());
        }
    #endif

Where `RD_KAFKA_MESSAGE_STATUS_SUPPORT_VERSION` corresponds to `v0.11.6` version of librdkafka. While the source tree under this tag in librdkafka repository doesn't support `rd_kafka_message_status()` yet. And I get compilation problems.

Am I looking for the wrong librdkafka version?

**Comment by avs009** [comment]
Same error here, the cppkafka requires RDKAFKA_MIN_VERSION 0x00090400, but this version not has 'rd_kafka_msg_status_t ' type yet!

This type will be introduced into master or v1.0RC in librbkafka.

**Comment by mfontanini** [comment]
True, could you create a PR and update the version (I presume 1.0 is a safe bet)?
