### ISSUE TITLE
compilation error when compiling against rdkafka 0.11.6

### ISSUE THREAD

**Issue by richardxu36** [mfontanini/cppkafka#169]
I get this error when trying to build cppkafka 0.3.0 against librdkafka 0.11.6 ([link](https://rpmfind.net/linux/RPM/remi/enterprise/6/x86_64/librdkafka-devel-0.11.6-1.el6.remi.x86_64.html)):

"""
[  4%] Building CXX object src/CMakeFiles/cppkafka.dir/configuration.cpp.o
In file included from /home/pxu1/cppkafka-0.3.0/src/../include/cppkafka/event.h:37:0,
                 from /home/pxu1/cppkafka-0.3.0/src/../include/cppkafka/configuration.h:45,
                 from /home/pxu1/cppkafka-0.3.0/src/configuration.cpp:30:
/home/pxu1/cppkafka-0.3.0/src/../include/cppkafka/message.h:208:5: error: 'rd_kafka_msg_status_t' does not name a type
     rd_kafka_msg_status_t get_status() const {
     ^
make[2]: *** [src/CMakeFiles/cppkafka.dir/configuration.cpp.o] Error 1
"""
 
I'm able to successfully against librdkafka 0.11.5([link](https://centos.pkgs.org/6/remi-x86_64/librdkafka-devel-0.11.5-1.el6.remi.x86_64.rpm.html)):

`cmake -DRDKAFKA_ROOT_DIR=/tmp/librdkafka-devel-0.11.5-1.el6.remi -DCPPKAFKA_CMAKE_VERBOSE=ON ..`

I'm building on a rhel6 host.

Has anyone experienced something similar?

**Comment by mfontanini** [comment]
This should be fixed on master, can you double check? I'll release v0.3.1 tonight to include that fix.

**Comment by richardxu36** [comment]
Thank you for the clarification, it compiles on master.

**Comment by mfontanini** [comment]
Just released [v0.3.1](https://github.com/mfontanini/cppkafka/releases/tag/v0.3.1). Sorry for the troubles!
