### ISSUE TITLE
Building with VS 2017 for x64 platform

### ISSUE THREAD

**Issue by oluf** [mfontanini/cppkafka#179]
I'm trying to build x64 static lib on windows 10 64 with Visual Studio 2017. The CMake configuration was updated to specify static libs.

I followed the instructions on the wiki up to the make step where I diverged.:
1. Boost 1.69 and rdkafka 0.11 x64 installed (shared)
2. Create and cd to the build folder
3. Run  the CMake command with updated paths - it finds boost and rdkafka and seems to complete successfully
4. I open the sln file in VS 2017
5. Set platform to x64 instead of win32
6. Try to build

This is where the process stops for me - the build fails with 41 errors and a few warnings, all related to utils/backoff_performer.cpp. A sample is included below:

1>D:\Projects\GitHub\cppkafka\src\utils\backoff_performer.cpp(42): warning C4003: not enough arguments for function-like macro invocation 'max'
1>D:\Projects\GitHub\cppkafka\src\utils\backoff_performer.cpp(42): error C2589: '(': illegal token on right side of '::'
1>D:\Projects\GitHub\cppkafka\src\utils\backoff_performer.cpp(42): error C2062: type 'unknown-type' unexpected
1>D:\Projects\GitHub\cppkafka\src\utils\backoff_performer.cpp(42): error C2143: syntax error: missing ';' before '}'
1>D:\Projects\GitHub\cppkafka\src\utils\backoff_performer.cpp(44): error C2653: 'BackoffPerformer': is not a class or namespace name
1>D:\Projects\GitHub\cppkafka\src\utils\backoff_performer.cpp(45): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>D:\Projects\GitHub\cppkafka\src\utils\backoff_performer.cpp(45): error C2065: 'DEFAULT_INITIAL_BACKOFF': undeclared identifier
1>D:\Projects\GitHub\cppkafka\src\utils\backoff_performer.cpp(46): error C2065: 'DEFAULT_BACKOFF_STEP': undeclared identifier
1>D:\Projects\GitHub\cppkafka\src\utils\backoff_performer.cpp(46): error C2065: 'DEFAULT_MAXIMUM_BACKOFF': undeclared identifier
1>D:\Projects\GitHub\cppkafka\src\utils\backoff_performer.cpp(47): error C2653: 'BackoffPolicy': is not a class or namespace name

I'm almost positive the problem is specific to me - I can't find any references to problems or issues related to this. I looked at CMakeCache.txt and all references are to x86 and win32, so I got wondering if the problem is related to trying to build for x64 with an x86 configuration. For example:
CMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3 /GR /EHsc
CMAKE_CXX_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
CMAKE_EXE_LINKER_FLAGS:STRING=/machine:X86

At this point I have to admit I'm stuck. Has anyone encountered this before? Any pointers? Or should I try to figure out how to build it with MingW?

**Comment by mfontanini** [comment]
This message:

```1>D:\Projects\GitHub\cppkafka\src\utils\backoff_performer.cpp(42): warning C4003: not enough arguments for function-like macro invocation 'max'```

Makes me think your project isn't using `NOMINMAX` (see [this link for reference](https://stackoverflow.com/questions/13416418/define-nominmax-using-stdmin-max/13420838)). Can you check if you have that set as a preprocessor option? The rest of the error messages could just be a consequence of that first one.

**Comment by oluf** [comment]
Thanks very much! That was the problem. Building for win32 is successful but building for x64 gives me a linker error now: 
x64\Debug\configuration.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'

I know that the target platform isn't what the build is configured for so I'm off to learn some more about CMake. I'll update when I've got it.

Thanks for your help.

**Comment by oluf** [comment]
OK got it, all I needed to do was add -DCMAKE_GENERATOR_PLATFORM=x64 and now, with NOMINMAX set, everything compiles successfully.
