### ISSUE TITLE
CPPKAFKA_VERSION_MINOR Not Updated

### ISSUE THREAD

**Issue by rriggs** [mfontanini/cppkafka#182]
I noticed the warning in the release notes for 0.3.0 that the ABI changed.  I would expect that the SONAME changes when the ABI changes.  Was this an oversight?  It seems a bump to CPPKAFKA_VERSION_MINOR is warranted when the ABI changes.

**Comment by mfontanini** [comment]
This was a (very bad) oversight on my side. I don't like altering history but I'll probably go back and re-tag 0.3.0 and 0.3.1 so they have the right soname.
