### ISSUE TITLE
set_stats_callback callback doesn't take optional parameter.

### ISSUE THREAD

**Issue by dnj12345** [mfontanini/cppkafka#186]
cppkafka::Configuration.set_stats_callback does not take an optional parameter. It only accepts a callback parameter. It'd be nice to allow the library user to store context information which can be returned when the callback is invoked. The librdkafka stats callback API allows for library user supplied optional parameter. The cppkafka callback handler signature includes a KafkaHandleBase handle, but the documentation is not clear on how this can be used by the users of the cppkafka library. A brief document explaining how this can be used or a code change that takes an optional parameter would be greatly appreciated.

Note: There's minor error in the 'configuration' documenation example page.

`
// Now configure it to be the default topic config
`
`
config.set_default_topic_config(topic_config);
`

The function is 'set_default_topic_configuration' and 'set_default_topic_config'. The example is correct on the producer example page :)

**Comment by accelerated** [comment]
There are a few ways to achieve what you want. For instance:
* Derive a class from `cppkafka::Consumer/Producer` and in that class you can hold whatever metadata you want. When the callback is invoked, you can `static_cast` the `KafkaHandleBase` into your derived class and access that metadata.
* Pass a lambda as a callback and capture whatever _external_ data you want which will then be accessible when the callback is called. 

Having your consumer or producer passed-in as part of the callback can be useful, as you can `get_metadata()` and access properties of the connection, maybe check your config via `get_configuration()` and take actions based on that, figure out the topic that's being serviced by the callback via `get_topic()` and with that topic you can lookup a map, etc...

**Comment by dnj12345** [comment]
> There are a few ways to achieve what you want. For instance:
> 
> * Derive a class from `cppkafka::Consumer/Producer` and in that class you can hold whatever metadata you want. When the callback is invoked, you can `static_cast` the `KafkaHandleBase` into your derived class and access that metadata.
> * Pass a lambda as a callback and capture whatever _external_ data you want which will then be accessible when the callback is called.
> 
> Having your consumer or producer passed-in as part of the callback can be useful, as you can `get_metadata()` and access properties of the connection, maybe check your config via `get_configuration()` and take actions based on that, figure out the topic that's being serviced by the callback via `get_topic()` and with that topic you can lookup a map, etc...

**Comment by dnj12345** [comment]
Thanks. Will follow your suggestion.
