### ISSUE TITLE
Creating Idempotent Producer in cppkafka

### ISSUE THREAD

**Issue by wbaizer** [mfontanini/cppkafka#188]
@mfontanini 

I am trying to set up an idempotent producer using cppkafka.

In my code I have set up the Configuration object as such:

```
  Configuration config = {
    { "metadata.broker.list", "127.0.0.1:9092" },
    { "message.send.max.retries",10000000 },
    { "acks", "all" },
    { "enable.idempotence", true }
  };
```
I compile my code like so:

`g++ producer.cpp -lcppkafka -o producer`

When I run my producer, I am getting this error:

```
terminate called after throwing an instance of 'cppkafka::ConfigException'
  what():  Failed to set enable.idempotence: No such configuration property: "enable.idempotence"
Aborted (core dumped)
```

Is cppkafka able to create an idempotent producer. If so, can you provide an example of how to do so?

Thanks

**Comment by accelerated** [comment]
My guess is that your rdkafka library is not up to date. This type of error has nothing to do with cppkafka as it's just a pass-through for configuration.

**Comment by wbaizer** [comment]
Thanks! I didn't realize I needed to run through this process (https://docs.confluent.io/current/installation/installing_cp/deb-ubuntu.html#get-the-software) to get the most up-to-date rdkafka.
