### ISSUE TITLE
include cppkafka

### ISSUE THREAD

**Issue by caseng** [mfontanini/cppkafka#19]
Hi, 

I am new working with protocols and I would like to use the librdkafka with your cppkafka client library. Unfortunately, I am not able to include your library correctly. I followed your instructions creating a build folder, run cmake and make on ubuntu 16.04. The commands run successfully. 
In the end the build/include folder only shows libcppkafka.so and libcppkafka.so.0.1. The rdkafka.h file or the librdkafka library are not shown as described in your readme file (_Note that finding librdkafka will succeed iff there's an include and lib directories inside the specified path, including both the rdkafka.h header and the librdkafka library file_.). 

Now I am wondering what I did wrong. Did I use the wrong directory for build? Has the cppkafka repository to be checked out inside the librdkafka repository? Or is anything else wrong/missing?
I am sorry asking this (probably simple) question but I hope you can help me anyway.

Thanks for your reply.

**Comment by mfontanini** [comment]
Normally you would install librdkafka (e.g. via `make install`). You're the third person that brings up the fact that this happens so maybe people don't install things anymore these days so I'll have to add some better detection for this.

You probably should install librdkafka anyway. Note that "install" doesn't mean copy it into `/usr/local` or some other global path. You can install libraries to local paths by using `./configure --prefix=some/local/path`.

**Comment by mfontanini** [comment]
Actually, this won't work. You *have* to install librdkafka. The include path after you install it looks like `librdkafka/rdkafka.h`. However, inside the source tree, that file is in `src/rdkafka.h`. If the structure was the same, then I could try to find it in the source tree but since that's not the case, that won't work.

**Comment by caseng** [comment]
Thank you for your reply. 
Librdkafka is installed correctly and I am able to include it using `librdkafka/rdkafka.h` in my projects as well.  But I think I have located the problem: The source tree in the librdkafka repository contains an additional src folder (not by default but added manually afterwards). So the file rdkafka.h is located in `src/src/rdkafka.h` and not - as it should be - in `src/rdkafka.h`. This is a fault of mine but because the librdkafka was not installed by myself and the additional src folder was added manually, I didn't look for dependencies for cppkafka in the librdkafka repository.
Thank you for your support!

**Comment by caseng** [comment]
Now I have installed librdkafka on a newly installed ubuntu 16.04 system but I am still not able to use cppkafka after following your instructions. 
This is the output I get after running `cmake ..` :

_-- Build will generate a static library.
-- Boost version: 1.58.0
-- Found valid rdkafka version
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
-- Disabling tests
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Libraries/cppkafka/build_


running `build` gets:
 _[100%] Built target cppkafka._

But after this either the library librdkafka nor the file rdkafka.h is shown and I am not able to include it in my project as well. 
Are there any other things to consider? Or do you have any other advice for me?
Thank you for your reply.

**Comment by mfontanini** [comment]
What do you mean that "rdkafka.h is not shown"? In your project you should be including rdkafka as well as cppkafka. Including cppkafka won't include rdkafka as well, they're different libraries.

**Comment by caseng** [comment]
Sorry for not replying sooner. 
I found the problem. It was not a fault of cppkafka but a local bug on qt. Now everything works fine.
Thank your for your support.
