### ISSUE TITLE
stats callback not invoked

### ISSUE THREAD

**Issue by dnj12345** [mfontanini/cppkafka#191]
Hi,
My stats callback is not getting invoked. It worked once but not anymore. Could someone let me know if I have an error? Thanks.

D.

librdkafka-ver: 0.11.6
libcppkafka: 0.3.1
OS: Ubuntu 16.04

```
#include <iostream>
#include <stdexcept>
#include <cstdlib>
#include <memory>

#include "cppkafka/producer.h"
#include "cppkafka/configuration.h"

using namespace std;

using cppkafka::Producer;
using cppkafka::Configuration;
using cppkafka::Topic;
using cppkafka::Message;
using cppkafka::MessageBuilder;
using cppkafka::KafkaHandleBase;

int
main (int argc, char *argv[])
{
  std::string topic;
  std::string broker;
  int partition = -1;
  char c;

  while ((c = getopt(argc, argv, "b:t:p:h")) != -1) {
    switch(c) {
      case 'b':
        broker = std::string(optarg);
        break;
      case 't':
        topic = std::string(optarg);
        break;
      case 'p':
        partition = std::atoi(optarg);
        break;
      case 'h':
        std::cout << "Usage: " << argv[0] << " -b <broker-name> -t <topic-name>\n";
        std::exit(-1);
      default:
        std::cout << "Invalid input params to " << argv[0] << '\n';
        break;
    }
  }

  if (topic.empty()) {
    std::cout << "Topic name must be provided\n";
    std::cout << "Usage: " << argv[0] << " -b <broker-name> -t <topic-name>\n";
    std::exit(-1);
  }

  if (broker.empty()) {
    std::cout << "Broker name must be provided\n";
    std::cout << "Usage: " << argv[0] << " -b <broker-name> -t <topic-name>\n";
    std::exit(-1);
  }

  // Create a message builder for this topic
  MessageBuilder builder(topic);

  // Get the partition we want to write to. If no partition is provided, this will be
  // an unassigned one
  if (partition != -1) {
      builder.partition(partition);
  }

  std::cout << "broker: " << broker << ", topic: " << topic << "\n";

  // Construct the configuration
  Configuration config = {
    { "metadata.broker.list", broker }
    , { "statistics.interval.ms", 5000 }
  };

  std::string mstats;
  auto stats_cb = [&](KafkaHandleBase& handle, const std::string& stats) {
                        std::cout << "stats callback invoked\n";
                        mstats = stats;
                      };

  config.set_stats_callback(stats_cb);

  // Create the producer
  Producer producer(config);
  cout << "Producing messages into topic " << topic << endl;

  // Now read lines and write them into kafka
  string line;
  while (getline(cin, line)) {
    if (line == "exit")
      break;

    if (line == "flush") {
      producer.flush();
      continue;
    }

    if (line == "stats") {
      cout << "stats: " << mstats << "\n";
      continue;
    }

    // Set the payload on this builder
    builder.payload(line);

    // Actually produce the message we've built
    producer.produce(builder);
  }

  // Flush all produced messages
  producer.flush();

  std::cout << "stats: " << mstats << "\n";

  // Create a message builder for this topic
  return 0;
}
```

**Comment by accelerated** [comment]
I think you need to have the flush inside the while loop.

**Comment by dnj12345** [comment]
> I think you need to have the flush inside the while loop. If the while does not get called continuously you still need to ensure that flush gets called continuously in order to raise all events.

Thanks, that worked. However, it seems strange I have to call flush. I thought it was a timer callback. 
If I set my interval to 10s and if I invoke flush call after 60 seconds after creating the producer, then my stats-callback gets invoked 6 times. Not sure if that's the intended behavior. Reading the docs, I thought the stats callback would be invoked every 10s.

btw, does flush close the connection to the broker? I ask this because I saw some message loss when I did a periodic flush. That problem went away when I remove the flush call.

**Comment by accelerated** [comment]
If you set the `statistics.interval.ms=10s` then every 10 secs rdkafka will take a statistics snapshot. When you call your flush after 60s, you will have 6 stats ready to be published, so that adds up. I don't think flush closes any connection. Register a delivery report callback and validate with that. You also have to poll continuously on the consumer side in order to see all events so maybe that's what happened in your case.

**Comment by dnj12345** [comment]
Thanks for the explanation. It's a bit different than what I am used to in terms of callbacks. What if I don't call publish at all, does it keep stashing the snapshots? is there an upper limit to how many it stores?

I did try the delivery report callback. The delivery callbacks were not consistent with the number of messages I had sent. I don't want to conflate loss issue with the stats issue. I'll create a separate issue for it once I have a repeatable test. Thanks for taking the time respond.
