### ISSUE TITLE
Windows Compiling

### ISSUE THREAD

**Issue by ozturksafa** [mfontanini/cppkafka#2]
I already faced with a lot of problems while compiling. I want to recommend a way to compile easily on Windows.

1. Install nuget
2. Install librdkafka and boost with following links:
                    https://www.nuget.org/packages/librdkafka.redist/
                    https://www.nuget.org/packages/boost
3. Compiling 
    mkdir build
    cd build
    cmake .. -DBOOST_INCLUDEDIR="<path_to_nuget>\nuget-3.5.0\boost.1.64.0.0\lib\native\include" 
    -DRDKAFKA_LIBRARY="<path_to_nuget>\nuget-3.5.0\librdkafka.redist.0.9.5\runtimes\win7-x64\native" 
    -DRDKAFKA_INCLUDE_DIR="<path_to_nuget>\nuget3.5.0\librdkafka.redist.0.9.5\build\native\include"
    make

**Comment by mfontanini** [comment]
Thanks! I'll add this to the wiki.

**Comment by mfontanini** [comment]
I just added this to the wiki. Thanks again!
