### ISSUE TITLE
`undefined reference to *` error on building consumer example

### ISSUE THREAD

**Issue by soheil08** [mfontanini/cppkafka#20]
Hi,
First I installed `librdkafka`  using instruction successfully. After that I installed `cppkafka` using document instruction, in addition command `sudo make install` at the end. So now both `librdkafka` and `cppkafka` are in directories `/usr/local/lib` and `/usr/local/include`. Trying to build `consumer` example code, the IDE(both Clion and Eclipse) resolved including libraries and show hints in using methods, but in building I faced error `undefined reference to` methods and classes. I check directory `/usr/local/include` and it only contains the `.h` files!

Did I do any steps wrong?

**Comment by mfontanini** [comment]
Did you run `sudo ldconfig` after installing both libraries?

**Comment by soheil08** [comment]
No, I did the following steps:

1. mkdir build

2. cd build

3. cmake ..

4. make

5. sudo make install

**Comment by mfontanini** [comment]
Try running `sudo ldconfig`, that's what you should run after installing
new libraries from source

**Comment by soheil08** [comment]
Thanks, I ran it. But still there is no `.cpp` file in directory `/usr/local/include/cppkafka`. It should be?

**Comment by mfontanini** [comment]
No, only header files (.h extension) should be in that directory. Wasn't
the issue that you were getting undefined references? Are you liking your
project with cppkafka and librdkafka by using -lcppkafka and -lrdkafa?

**Comment by soheil08** [comment]
No, I didn't link my project to `cppkafka` and `lrdkafka`. Can you clarify that pls? Thanks

**Comment by mfontanini** [comment]
Add `-lcppkafka -rdkafka` to your link options

**Comment by soheil08** [comment]
Thanks for your answering. You know I'm C++ coder but totally newbie to making libraries.
I created a project using `clion` and run code there. Can you say more details how and where I should link them? In which step?

Thanks in advanced

**Comment by soheil08** [comment]
Which one should I link to?  `cppkafka` and `rdkafka` I downloaded from github or  `cppkafka` and `rdkafka` created in path `/usr/local/include` after doing make?

**Comment by mfontanini** [comment]
I have never used CLion. Search for how to configure the compiler link flags and add "-lcppkafka -lrdkafka" to them.

**Comment by soheil08** [comment]
Thanks, now it errors `undefined reference to boost::program_options::options_description::m_default_line_length'|`

it's because of boost
How can I fix that?

**Comment by mfontanini** [comment]
`-lboost_program_options`. Are you just trying to build the example? Just
run `make kafka_example` inside cppkafka's `build` directory

**Comment by soheil08** [comment]
That's it, using -lboost_program_options, It works
Thanks a lot!!!!!!!!!!!

**Comment by gbxu** [comment]
i have the same problem. 
i install rdkafka and cppkafka, then i write `main.cpp`

```cpp
#include <cppkafka/producer.h>
using namespace std;
using namespace cppkafka;
int main() {
    // Create the config
    Configuration config = {
        { "metadata.broker.list", "127.0.0.1:9092" }
    };

    // Create the producer
    Producer producer(config);

    // Produce a message!
    string message = "hey there!";
    producer.produce(MessageBuilder("my_topic").partition(0).payload(message));
    producer.flush();
}
```
i write the `CMakeLists.txt` as follows:
```bash
cmake_minimum_required(VERSION 3.10)
project(test)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lrdkafka++ -lrdkafka -lcppkafka")
add_executable(test main.cpp)
```
but when i compile and run the `main.cpp`
it shows:
```
undefined reference to `cppkafka::ConfigurationOption::ConfigurationOption(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*)'
undefined reference to `cppkafka::Configuration::Configuration(std::initializer_list<cppkafka::ConfigurationOption> const&)'
...
```
what did i miss?
gcc 5.4 
ubuntu 16.04

**Comment by gbxu** [comment]
I solve it. I should learn how to use cmake!
I modify the `CMakeLists.txt`
```
cmake_minimum_required(VERSION 3.10)
project(test)
set(CMAKE_CXX_STANDARD 11)
include_directories("/usr/local/include/librdkafka")
include_directories("/usr/local/include/cppkafka")
FIND_LIBRARY(RDKAFKA rdkafka /usr/local/lib NO_DEFAULT_PATH)
FIND_LIBRARY(CPPKAFKA cppkafka /usr/local/lib NO_DEFAULT_PATH)
link_libraries(${RDKAFKA} ${CPPKAFKA})
add_executable(test src/main.cpp)
target_link_libraries(test cppkafka)
target_link_libraries(test rdkafka)
```
now It works well!

**Comment by mfontanini** [comment]
I think you just had to run `ldconfig` as root right after installing cppkafka.

**Comment by gbxu** [comment]
@mfontanini  I runned `sudo ldconfig` before. and the `CMakeLists.txt` is as follows: 
```
cmake_minimum_required(VERSION 3.10)
project(test)
set(CMAKE_CXX_STANDARD 11)
add_executable(test src/main.cpp)
```
The problem  happens.
I try the steps again and get the same result. It bothers me.
