### ISSUE TITLE
consumer.poll have different behaviors in ubuntu and centos

### ISSUE THREAD

**Issue by yjhmelody** [mfontanini/cppkafka#202]
When in centos, I always get one `no more message` after getting one normal message.

`if(msg)` always be true, but msg.get_error() has a different value in ubuntu and centos.

**Comment by accelerated** [comment]
Hi, this has nothing to do with this library which is a thin wrapper on top or RdKafka. Furthermore, many things can vary...are you using the same RdKafka library versions on ubuntu and centos? Is the configuration identical on both, etc...
