### ISSUE TITLE
How do I pass a structure instead of string through kafka?

### ISSUE THREAD

**Issue by pradeepp2019** [mfontanini/cppkafka#203]
Getting the below error when I am trying to pass structure instead of string. Do I have to do any modification? Any help would be appreciated. This is producer_example.cpp. Also, I would like to know from consumer perspective too. Thanks!

Code Snippet:
----------------
struct User
{
    string username;
    string password;
};

    User obj;
    obj.username = "test";
    obj.password = "test123";

    while (getline(cin, line)) {
        // Set the payload on this builder
        //builder.payload(line);
        builder.payload(obj);   -----> Error here

        // Actually produce the message we've built
        producer.produce(builder);
    }
Error:
------
/home/pradeep/code/cppkafka-0.3.1/examples/producer_example.cpp: In function ‘int main(int, char**)’:
/home/pradeep/code/cppkafka-0.3.1/examples/producer_example.cpp:83:28: error: no matching function for call to ‘cppkafka::MessageBuilder::payload(User&)’
         builder.payload(obj);
                            ^
In file included from /home/pradeep/code/cppkafka-0.3.1/examples/../include/cppkafka/producer.h:39,
                 from /home/pradeep/code/cppkafka-0.3.1/examples/producer_example.cpp:4:
/home/pradeep/code/cppkafka-0.3.1/examples/../include/cppkafka/message_builder.h:339:4: note: candidate: ‘C& cppkafka::BasicMessageBuilder<BufferType, Concrete>::payload(const T&) [with BufferType = cppkafka::Buffer; Concrete = cppkafka::MessageBuilder]’
 C& BasicMessageBuilder<T, C>::payload(const T& value) {
    ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/pradeep/code/cppkafka-0.3.1/examples/../include/cppkafka/message_builder.h:339:4: note:   no known conversion for argument 1 from ‘User’ to ‘const cppkafka::Buffer&’
/home/pradeep/code/cppkafka-0.3.1/examples/../include/cppkafka/message_builder.h:345:4: note: candidate: ‘C& cppkafka::BasicMessageBuilder<BufferType, Concrete>::payload(T&&) [with BufferType = cppkafka::Buffer; Concrete = cppkafka::MessageBuilder]’
 C& BasicMessageBuilder<T, C>::payload(T&& value) {
    ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/pradeep/code/cppkafka-0.3.1/examples/../include/cppkafka/message_builder.h:345:4: note:   no known conversion for argument 1 from ‘User’ to ‘cppkafka::Buffer&&’
/home/pradeep/code/cppkafka-0.3.1/examples/../include/cppkafka/message_builder.h:405:10: note: candidate: ‘const T& cppkafka::BasicMessageBuilder<BufferType, Concrete>::payload() const [with BufferType = cppkafka::Buffer; Concrete = cppkafka::MessageBuilder]’
 const T& BasicMessageBuilder<T, C>::payload() const {
          ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/pradeep/code/cppkafka-0.3.1/examples/../include/cppkafka/message_builder.h:405:10: note:   candidate expects 0 arguments, 1 provided
/home/pradeep/code/cppkafka-0.3.1/examples/../include/cppkafka/message_builder.h:410:4: note: candidate: ‘T& cppkafka::BasicMessageBuilder<BufferType, Concrete>::payload() [with BufferType = cppkafka::Buffer; Concrete = cppkafka::MessageBuilder]’
 T& BasicMessageBuilder<T, C>::payload() {
    ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/pradeep/code/cppkafka-0.3.1/examples/../include/cppkafka/message_builder.h:410:4: note:   candidate expects 0 arguments, 1 provided
make[3]: *** [examples/CMakeFiles/producer.dir/producer_example.cpp.o] Error 1
make[2]: *** [examples/CMakeFiles/producer.dir/all] Error 2
make[1]: *** [examples/CMakeFiles/producer.dir/rule] Error 2
make: *** [examples/CMakeFiles/producer.dir/rule] Error 2

**Comment by pradeepp2019** [comment]
Able to fix it by below code..
    const char* ptr = reinterpret_cast<const char*>(obj);
    builder.payload({ ptr, sizeof(User) });

But I am facing issue in consumer where I am unable to get the structure from Buffer class object. 
Any help about it would be appreciated. It looks like some casting issue.

/home/pradeep/code/cppkafka-0.3.1/examples/consumer_example.cpp: In function ‘int main(int, char**)’:
/home/pradeep/code/cppkafka-0.3.1/examples/consumer_example.cpp:108:76: error: invalid cast from type ‘const cppkafka::Buffer’ to type ‘User*’
                 const User* obj = reinterpret_cast<User*>(msg.get_payload());

**Comment by accelerated** [comment]
You cannot simply cast an object to a char* and hope that it works. Any data you pass into cppkafka will have to be serialized in the producer and deserialized by the consumer. You can use frameworks like [Avro](https://avro.apache.org/) or [Flatbuffers](https://google.github.io/flatbuffers/) to handle this for you. Otherwise you can also serialize them yourself if your data structure is not too complicated.

**Comment by pradeepp2019** [comment]
Thanks @accelerated for the response. I am able to pass structures from producers to consumers by serializing/deserializing using protobuf.
