### ISSUE TITLE
Is it possible to create a topic with specific partition number

### ISSUE THREAD

**Issue by soheil08** [mfontanini/cppkafka#23]
Hi, I know Kafka creates topic when producing the messages if the topic did not exist. In this situation, Kafka creates topic using default configs like `num.partitions`. 

I want to create my desired topic, if not exist, with my desired partitions without changing default configurations. Is it possible using the `cppkafka`?

**Comment by mfontanini** [comment]
This is more of a question for `librdkafka`. If that's supported on librdkafka, then it will work on cppkafka.
