### ISSUE TITLE
sending char[] data type as a message

### ISSUE THREAD

**Issue by soheil08** [mfontanini/cppkafka#24]
Hi,

How can I send messages in type `char[]`?

Is it required messages to be just in `string` format?

I tried creating messages in `char[]` type but I faced error!
`char buf[2000];`

`builder.payload(buf);`

and I should convert it to `string`

`char buf[2000];`

`string temp = buf;`

`builder.payload(string);`

**Comment by mfontanini** [comment]
The payloads are represented using the `Buffer` class. You can construct a buffer from a pointer and a size:

```c++
builder.payload({ buf, sizeof(buf) });
```

**Comment by soheil08** [comment]
Thanks!
