### ISSUE TITLE
sending unsigned char[] to kafka

### ISSUE THREAD

**Issue by soheil08** [mfontanini/cppkafka#25]
I want to write `unsigned char[]` to Kafka. The original message is `char[]` and when I print it, it contains some extra character, for example:
`char buf[2000];`
`for (int i =0 ; i < 2000; i++)
        {
            printf(" ");
            printf("%02x", buf[i]);
        }`
it contains :
`EF  BF  BD  01  00  1C  1E  39  5A  18  40  EF  BF  BD  00  38  51  EF  BF  BD  00  00  EF  BF  BD  EF  BF  BD  00  48  00  EF  BF  BD  00  00  00  64  EF  BF  BD  1F`, 
extra `EF  BF  BD` pattern that are not in general pattern. To avoid this to happen, I tried:
`for (int i =0 ; i < 2000; i++)
        {
            printf(" ");
            printf("%02x", (unsighed char)buf[i]);
        }`, and the general message is printing in correct format.

When I attempted to send `buf` to Kafka, I tried

`builder.payload({(unsighend char*)buf, 2000});`

But it is written to Kafka in the wrong format, in the format that extra `EF  BF  BD` pattern included in the message!

How can send data to Kafka so that save in original message format?

**Comment by mfontanini** [comment]
How do you know the message is in the wrong format? Couldn't you just be printing the message in the same erroneous way? Using a payload will copy it "as is" so there won't be any change in it whatsoever in the produced messages.

**Comment by soheil08** [comment]
Ok, That's right!
