### ISSUE TITLE
Unable to set/use BackgroundEventCallback

### ISSUE THREAD

**Issue by 196884** [mfontanini/cppkafka#268]
The signature specifies a cppkafka::Event as the second argument, but that object is not copyable (implicitly deleted, as it uses an std::unique_ptr which itself is not copyable...). Would it make sense to pass a const cppkafka::Event& instead?

**Comment by mfontanini** [comment]
That callback takes an `Event` so you should be able to move it. e.g. `events.push_back(move(event));`

**Comment by 196884** [comment]
Arf, yes, thanks!
