### ISSUE TITLE
Topic creation

### ISSUE THREAD

**Issue by chenziliang** [mfontanini/cppkafka#270]
Hi,

I didn't see there is a wrapper for topic creation etc admin APIs from librdkafka. Would like to confirm this is the case.

Thanks !

**Comment by mfontanini** [comment]
I had started working on that in [this branch](https://github.com/mfontanini/cppkafka/tree/admin-api) but I didn't get to finish it. I think I managed to implement most of the API but there's still a few things missing.

**Comment by chenziliang** [comment]
Thanks a lot

**Comment by chenziliang** [comment]
BTW, may i ask the thread safety property of producer / consumer ? I know librdkafka's APIs are usually thread safe, but like to confirm this is still the case in cppkafka. Thanks a lot

**Comment by accelerated** [comment]
Yes they are and so is the buffered producer.
