### ISSUE TITLE
How can i run the example when i compile project success.

### ISSUE THREAD

**Issue by jiakai908** [mfontanini/cppkafka#274]
1. `MacBook-Pro:build xxxx$ make install`

[ 66%] Built target cppkafka
[100%] Built target cppkafka_tests
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/lib/libcppkafka.0.3.1.dylib
-- Installing: /usr/local/lib/libcppkafka.dylib
-- Installing: /usr/local/share/pkgconfig/cppkafka.pc
-- Installing: /usr/local/lib/cmake/CppKafka/CppKafkaTargets.cmake

2. run the example in c++ ide (clion)
/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --build /Users/xxxx/project/c++/cppkafka/cmake-build-default --target metadata -- -j 12
[ 92%] Built target cppkafka
[ 96%] Linking CXX executable metadata
Undefined symbols for architecture x86_64:
  "boost::program_options::to_internal(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > boost::program_options::to_internal<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) in metadata_example.cpp.o
  "boost::program_options::options_description::options_description(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)", referenced from:
      _main in metadata_example.cpp.o
  "boost::program_options::detail::cmdline::cmdline(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)", referenced from:
      boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*) in metadata_example.cpp.o
  "boost::program_options::validate(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)", referenced from:
      boost::program_options::typed_value<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const in metadata_example.cpp.o
  "boost::program_options::operator<<(std::basic_ostream<char, std::char_traits<char> >&, boost::program_options::options_description const&)", referenced from:
      _main in metadata_example.cpp.o
  "boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const", referenced from:
      vtable for boost::program_options::typed_value<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, char> in metadata_example.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[3]: *** [examples/metadata] Error 1
make[2]: *** [examples/CMakeFiles/metadata.dir/all] Error 2
make[1]: *** [examples/CMakeFiles/metadata.dir/rule] Error 2
make: *** [metadata] Error 2

**Comment by ladislavmacoun** [comment]
you're missing boost library for program options

**Comment by jiakai908** [comment]
@ladislavmacoun how to solve it.

**Comment by ladislavmacoun** [comment]
@jiakai908 install libboost with your favorite package manager for example with brew

`brew install boost`
