### ISSUE TITLE
It is possible to change topic for MessageBuilder object

### ISSUE THREAD

**Issue by soheil08** [mfontanini/cppkafka#29]
Consider the code blow:

`MessageBuilder builder (str); // str is a topic name.`

now I want to change the topic for builder:
`builde(new_str);  // new_str is another topic`

But this is errorful. Is there any way to set another topic for `builder`?

**Comment by mfontanini** [comment]
Use `builder.topic("other topic")`

**Comment by soheil08** [comment]
Thanks!
