### ISSUE TITLE
How to produce data asynchrony

### ISSUE THREAD

**Issue by soheil08** [mfontanini/cppkafka#30]
Hey,

In the producer example, messages are sent to brokers using command `producer.produce(builder);`.
As you know Kafka provides three strategies for sending data, `fire and forget`, `synchronous` and `asynchronous`. Using cppkafka is it possible to produce messages in `asynchronous` mode?

**Comment by mfontanini** [comment]
_librdkafka_ always produces messages asynchronously. If you want to ensure they are actually acknowledged by the brokers you should configure a delivery report callback on your `Configuration` object.
