### ISSUE TITLE
How can I set debug configuration property

### ISSUE THREAD

**Issue by soheil08** [mfontanini/cppkafka#31]
I have a CppKafka producer code that I run the program using command:
`./connector -b kafka1:9092,kafka2:9092,kafka3:9092` 
Now I want to run it in debug mode with properties `metadata,topic,msg`, how can I do that using CppKafka?

**Comment by mfontanini** [comment]
You can use the "debug" configuration attribute when creating your
`Configuration` object.

**Comment by soheil08** [comment]
Thanks for your reply!

You mean this part of code:
`Configuration config = {
        { "metadata.broker.list", brokers }
    };`

Can you give me an example of creating debug mode in this code?
How should I run it? Just like before? `./connector -b kafka1:9092,kafka2:9092,kafka3:9092`

**Comment by soheil08** [comment]
using code below it solved:
`Configuration config = {
            {"metadata.broker.list", brokers},
                {"debug", "broker,topic,msg"}
    };
`

Thanks!
