### ISSUE TITLE
What happens if Kafka was offline ?

### ISSUE THREAD

**Issue by TheSharpOwl** [mfontanini/cppkafka#311]
In case I got a producer in the code and it's sending messages but the Kafka server is offline (not the consumer), does it buffer stuff ? and if yes what is the limit ? and can that limit be set ?

seems to me yes it will store locally if I don't call `flush()` (but don't know the limit) 

Please also correct me if I am wrong. 
Sorry if it's already answered because I tried to google it and couldn't find my answer.

**Comment by mfontanini** [comment]
cppkafka is a dumb wrapper over [rdkafka](https://github.com/confluentinc/librdkafka). Please look at their documentation / ask this question in their bug tracker. Thanks!
