### ISSUE TITLE
Writing failed message on a file

### ISSUE THREAD

**Issue by soheil08** [mfontanini/cppkafka#32]
Hey, I want to write a callback function that writes failed messages to a file. Is it possible using `CppKafka` and if yes what method can I use? Is this approach an standard policy facing not delivered messages?

**Comment by mfontanini** [comment]
How you handle that depends on the application you're implementing. Some may be okay with losing a message, some may not. rdkafka will attempt to re-send the message multiple times before failing. If it fails, you can set a delivery report callback on the `Configuraion` object (check the docs or configuration.h header file). Then you can check if the message delivery succeeded or not and act appropriately.

**Comment by soheil08** [comment]
I worried about you because you always answer the questions in on day at most but this time you were not here. I am happy that you came back. Thanks, generous man!
