### ISSUE TITLE
How to send binary data by cppkafka library?

### ISSUE THREAD

**Issue by feifeidadi** [mfontanini/cppkafka#35]
Hi,

Thank you for your great job for this c++ wrapper of librdkafka.

I can successfully send text messages to Kafka broker by examples/kafka_producer.cpp program, but nothing can be received in the consumer side while I managed to send binary data as follows (codes modified basing on kafka_producer.cpp):

```c++
///////////////////////////////////////
    // Create the producer
    Producer producer(config);

#if 1  // Binary payload seems failed.
    cout << "Sending CDR to kafka broker..." << endl;
    unsigned char* buf = NULL;
    int length = 0;

    loadCdrContent(buf, length);
    Buffer buffer(buf, length);
    builder.payload(buffer);

    producer.produce(builder);
    // TODO: free memory
#else // String payload can be sent successfully
    cout << "Producing messages into topic " << topic_name << endl;
    // Now read lines and write them into kafka
    string line;
    while (getline(cin, line)) {
        // Set the payload on this builder
        builder.payload(line);

        // Actually produce the message we've built
        producer.produce(builder);
    }
#endif

///////////////////////////////////////
int loadCdrContent(unsigned char* &buffer, int &length) {
    std::ifstream is ("./CDR.ber", std::ifstream::binary);
    is.seekg (0, is.end);
    length = is.tellg();
    is.seekg (0, is.beg);

    buffer = new unsigned char [length];
    is.read((char *)buffer, length);

    cout << "Buffer length is " << length << endl;

    is.close();

    return 0;
}
```

Do you have any suggestion on this issue? Is the above code of sending binary payload correct?
Btw, buffer.get_data() and buffer.get_size() returns correct value.

Best reagards,
Mike

**Comment by mfontanini** [comment]
Could you come up with a short reproducible code I can use to test this? I've been using cppkafka to send protobuf messages (they serialize as binary data) so this definitely works. 

Are the messages successfully sent? Are you waiting for the messages to be sent or are you closing your producer right after sending? You may want to wait for your produced messages to be acked.

**Comment by feifeidadi** [comment]
Hi Matias Fontanini,

Thanks a lot for your reply.
You are right. It sends the binary buffer successfully after waiting for a moment after `producer.produce(builder);`.

Best regards,
Mike

**Comment by mfontanini** [comment]
That's great. Note that you can use the [BufferedProducer](https://github.com/mfontanini/cppkafka/blob/master/include/cppkafka/utils/buffered_producer.h) class which, besides allowing to buffer and produce message, it also lets you wait until they're acked. It's almost a drop-in replacement for `Producer`, see [this test](https://github.com/mfontanini/cppkafka/blob/master/tests/producer_test.cpp#L240) where it's used. Then just call `produer.flush()` and that'll wait until messages are acked by the kafka broker(s).

**Comment by feifeidadi** [comment]
Hi Matias Fontanini,

Thank you for your quick response :).

Does it mean that the BufferedProducer class works in asynchronous mode by default? 
In case of producer.flush() is not called, the delivery status needs to be checked in the delivery report callback, right?

Best regards,
Mike

**Comment by mfontanini** [comment]
It can actually work both ways: if you call `BufferedProducer::produce`, the message is produced as usual (asynchronously). If you call `BufferedProducer::add_message`, then the message is queued internally and only actually sent to kafka when calling `flush`. That call will block until all messages are actually acked.

**Comment by feifeidadi** [comment]
OK, it's clear enough. Thanks a lot for your explanation Matias Fontanini.

Best regards & happy weekend,
Mike
