### ISSUE TITLE
 Failed to find valid rdkafka version when trying to compile cppkafka

### ISSUE THREAD

**Issue by dk1301** [mfontanini/cppkafka#43]
Hi all,
I'm trying to build cppkafka on a vm ubuntu 16.04 amd64 with gcc 5.0.4 , cmake 3.10.0 and Boost 1.63.0 . I've built librdkakfa version v0.11.3.
In a local folder I've created two subfolders , include and lib. The include contains rdkafka.h and the lib the librdkafka.so.1. 
When I try to build the cppkafka with the following  command : 
`cmake .. -DRDKAFKA_ROOT_DIR=/home/user/local_folder -DRDKAFKA_LIBRARY=/home/user/local_folder/lib -DRDKAFKA_INCLUDE_DIR=/home/user/local_folder/include`
I get the following printout:

```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build will generate a shared library. Use CPPKAFKA_BUILD_SHARED=0 to perform a static build
-- Boost version: 1.63.0
-- Found RDKAFKA: /home/user/local_folder/lib  
CMake Error at cmake/FindRdKafka.cmake:39 (message):
  Failed to find valid rdkafka version
Call Stack (most recent call first):
  CMakeLists.txt:40 (find_package
```)

What am I doing wrong here?

**Comment by mfontanini** [comment]
The easiest way to set up librdkafka properly is to just configure it using `--prefix` and then install it. e.g.:

```
cd librdkafka
./configure --prefix=/home/user/local_folder
make
make install
```

Now the library is installed into `/home/user/local_folder`. Then the command above should work.

**Comment by dk1301** [comment]
This worked perfect. Thanks for the help. one last question though. With this way in local_folder both c and c++ librdkafka are created.  When in Using part of the documentation is stated that:
```
If you want to use cppkafka, you'll need to link your application with:
cppkafka
rdkafka
```
The rdkafka is reffering to c or the c++ version?

**Comment by mfontanini** [comment]
It refers to the C version. cppkafka is a wrapper the librdkafka C API, not the C++ one. So basically you need to use `-lcppkafka -lrdkafka` as your link flags (besides any other ones like `-L` for the directory where rdkafka is installed).

**Comment by dk1301** [comment]
Thanks again for your support.
