### ISSUE TITLE
Question about payload alignment and padding.

### ISSUE THREAD

**Issue by nleclercq** [mfontanini/cppkafka#46]
Hi,
Does cppkafka take care of data alignment and padding when pushing/pulling data for a topic? Suppose I have a struct (with several fields) I want to inject into a message as the payload, what do I need to do in terms of data alignment and/or padding? Does your lib (or the underlying one) provides the tools for that? Thanks.

**Comment by mfontanini** [comment]
Nothing special is done with the data both on the producer and consumer sides. Both the key and the payload are just a chunk of bytes. You can serialize/deserialize that however you want on each side.

**Comment by nleclercq** [comment]
I see. Thanks.
