### ISSUE TITLE
QUESTION: Development model

### ISSUE THREAD

**Issue by EvilBeaver** [mfontanini/cppkafka#50]
Hi! Thanks for the lib!

One question: if I want to use this lib as a submodule. Where is 'stable' branch or commit?
Now it has only one tag v0.1 and it's release date is quite old (6.6.2017)
Is it only one stable point of code or branch 'master' is also stable enough?

**Comment by mfontanini** [comment]
I should actually release a new version soon, there's been several minor fixes. You can safely use master for now, its stable.
