### ISSUE TITLE
Error linking into DLL on Windows

### ISSUE THREAD

**Issue by EvilBeaver** [mfontanini/cppkafka#57]
Got linking error on VS 2017.

* Project is Win32 DLL generated from CMAKE
* both librdkafka and cppkafka are built with cmake and installed on D:\lib\rdkafka and D:\lib\cppkafka respectively
* both librdkafka.lib and cppkafka.lib are linked in Win32 DLL in project options. Here's linker additional dependencies: 

```
  D:\lib\boost\lib\libboost_iostreams-vc141-mt-x32-1_67.lib
  D:\lib\boost\lib\libboost_zlib-vc141-mt-x32-1_67.lib
  ws2_32.lib
  D:\lib\librdkafka\lib\rdkafka.lib
  D:\lib\cppkafka\lib\cppkafka.lib
```

* Linker says it cant'find anything that cppkafka references in the librdkafka:

**cppkafka.lib(configuration.obj)** > unresolved external symbol __imp__rd_kafka_conf_new referenced in function "public: __thiscall cppkafka::Configuration::Configuration(void)" : 
**cppkafka.lib(configuration.obj)** > unresolved external symbol __imp__rd_kafka_conf_destroy referenced in function "private: __thiscall cppkafka::Configuration::Configuration(struct rd_kafka_conf_s *)"

Bold text is the obj file that references librdkafka.lib It seems Linker **can't find any of librdkafka.lib symbols**. Any ideas why? librdkafka.lib exists in the linker keys....

What is the proper way to link static cppkafka.lib (along with librdkafka.lib) into another app?

**Comment by warales** [comment]
I am facing same issue..checked all linker settings and incompatibilities ..all is ok...any clue ?

**Comment by EvilBeaver** [comment]
This was fixed by @dmpas and merged into main repo AFAIK
