### ISSUE TITLE
Question on rd_kafka_wait_destroyed

### ISSUE THREAD

**Issue by accelerated** [mfontanini/cppkafka#60]
I notice that your library is not calling the _optional but highly recommended_ `rd_kafka_wait_destroyed()`. Would it be worth implementing either some static method which users could call directly to destroy the library or even better an RAII object which upon scope exit would call rd_kafka_wait_destroyed ?

**Comment by mfontanini** [comment]
Do you have any references that say it's "highly recommended"? It seems like it's [marked as deprecated](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L3411).

**Comment by accelerated** [comment]
Ah...now I see it. I was checking the c++ examples in librdkafka and they were not marked as deprecated. See [here](https://github.com/accelerated/librdkafka/blob/master/examples/rdkafka_consumer_example.cpp#L482) or [here](https://github.com/accelerated/librdkafka/blob/master/examples/rdkafka_example.cpp#L642). I assumed it was good practice to properly shutdown the library. So far I haven't had any issues with your wrappers but i was just wondering if it's necessary to call it.

**Comment by mfontanini** [comment]
Ah okay. I haven't had any issues with cleanups so unless there's some apparent memory leak or something like that, I think there's no need to do anything extra.

**Comment by accelerated** [comment]
@mfontanini thanks!!
