### ISSUE TITLE
Enhancement: internal counter in the message type

### ISSUE THREAD

**Issue by accelerated** [mfontanini/cppkafka#69]
@mfontanini It would be nice to add a feature to be able to supply the number of times a backoff committer should retry (not based on time) and same thing for the buffered producer. I was thinking to add a counter inside the message which would monotonically increase, and the backoff committer would increment this value each time it fails. This won't work however with the producer since the delivery callback creates non-owning temporaries, so each time the counter would be reset. But at least the sync committer would work. 
Alternatively the application could keep a map of message handles and counters, but that's a bit overkill. Any suggestions on adding such a feature?

**Comment by mfontanini** [comment]
Can't you achieve this already by using the callback in the `BackoffCommitter`?

**Comment by mfontanini** [comment]
But you call `commit` on a single message, so you know which message you're trying to commit.

**Comment by accelerated** [comment]
Yes I would have to add a setter and some logic inside `backoff_performer::perform()` to count. For commits it's easy as the calls are synchronous but the buffered producer is a bit trickier as the retry runs off the `on_delivery_report` callback.

**Comment by accelerated** [comment]
One more thing...the buffered producer is not thread safe due to the underlying unprotected vector. I assume in your case you may not have needed that but I would definitely like to be able to produce from various threads. librdkafka is supposedly thread safe so it would make sense to have the buffered producer thread safe as well.

**Comment by accelerated** [comment]
Hi @mfontanini, please let me know if you would accept making this class thread safe and if so I can submit a PR. Otherwise I have to synchronize at the class level and think of some other design. Also do you have an ETA on the other PRs? I'm currently working with 5 different branches and I have to cherry-pick commits into a temp branch but since I don't know if I can rely on them it makes coding more complicated.

**Comment by mfontanini** [comment]
Yeah, adding a mutex would work. I don't have too much time so I check things whenever I have some. I'll try to review the rest of them soon.

**Comment by accelerated** [comment]
Ok I will submit the PR, thanks! Doing lots of dev now on top of your library so you may see a few more PRs in the coming days, although most of the stuff I needed changed is done.
