### ISSUE TITLE
How to deliver message with different topic in one routine

### ISSUE THREAD

**Issue by feifeidadi** [mfontanini/cppkafka#71]
Hi,

I am writing a piece of code to send different topic messages to kafka cluster.
But the program got stuck in the producer.poll() API while sending the second topic's message...

The message sending function is as follows:

```c++
int kafkaProducer::produceMessage(u8_t* pBuffer, u32_t length, string &topic_name)
{
    MessageBuilder builder(topic_name);
    //builder.topic(topic_name);

    Configuration config = {
        { "metadata.broker.list", kafkaBrokers },
        { "queue.buffering.max.messages", MAX_BUFFERING_MESSAGES}
    };
    config.set_delivery_report_callback(deliveryReportCallback);
    Producer producer(config);

    Buffer buffer(pBuffer, length);
    builder.payload(buffer);
    //TODO: free pBuffer, // maybe in deliveryReportCallback ?

    producer.produce(builder);

    while (producer.get_out_queue_length() > 0) {
        producer.poll();
    }

    return 0;
}
```

Execution scenario is as follows:
```c++
    string topic1 = "topic1", topic2 = "topic2"
    produceMessage(..., topic1); // fine
    produceMessage(..., topic2); // Got stuck in producer.poll()
```

I managed to use BufferedProducer instead, but got the same result...
And it works fine if I send multiple messages to the same topic.

Thanks,
Mike Xu

**Comment by feifeidadi** [comment]
It works after newly creating two another two topics ...

Will this problem be related with Kafka broker? Does anyone meet similar issue before? Are there any suggestion of avoiding such kind of issue?

Thanks,
Mike Xu

**Comment by mfontanini** [comment]
I haven't had this issue before. Maybe you could turn on the logs (using the `debug` configuration option, see [this](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)) and see what they say.

**Comment by feifeidadi** [comment]
Ok, I'll monitor this issue continuously.
Thanks anyway and maybe you can close this issue for this moment.

Best regards,
Mike Xu

**Comment by feifeidadi** [comment]
Hi,

Here is an additional question... Will the producer free the pre-allocated memory (at line 81) finally?

 81     char* pBuffer = new char[50];
 82     strcpy(pbuffer, "testing");
 83     MessageBuilder builder(topic_name);
 84     BufferedProducer<string> producer(config);
 85     producer.set_produce_failure_callback(produceFailureCallback);
 86     Buffer buffer(pBuffer, length);
 87     builder.payload(buffer);
 88     producer.add_message(builder);
 89     producer.flush();
 90     producer.produce(builder);
 91     producer.wait_for_acks();

Best regards,
Mike Xu

**Comment by feifeidadi** [comment]
ok, default is copy payload, so the payload needs to be freed manually.

===
    /**
     * The policy to use for the payload. The default policy is COPY_PAYLOAD
     */
    enum class PayloadPolicy {
        COPY_PAYLOAD = RD_KAFKA_MSG_F_COPY, ///< Means RD_KAFKA_MSG_F_COPY
        FREE_PAYLOAD = RD_KAFKA_MSG_F_FREE  ///< Means RD_KAFKA_MSG_F_FREE
    };
===

Best regards,
Mike Xu
