### ISSUE TITLE
release versioning

### ISSUE THREAD

**Issue by sachnk** [mfontanini/cppkafka#80]
Hey --

I'm currently using a clone of master in my project from last week. But I noticed that there were some commits into master recently.

Is it possible to use GitHub's tag / release feature so that we can consistently download a snapshot of a particular version? Right now, I see there is only 1 release from awhile ago.

Thanks!

**Comment by mfontanini** [comment]
Yes, you should check out specific tags if possible. I'll release a new version soon but there's still a few changes in review and a couple of things I want to try implementing before doing so, which may delay the release a bit.

**Comment by ccf** [comment]
Any word on that release? It's been a bit and a few commits...

**Comment by mfontanini** [comment]
Yeah sorry, I've not been paying too much attention to this project, my bad. I'll make sure to release a version later today. Sorry for the delay!
