### ISSUE TITLE
 undefined reference to `cppkafka::ConfigurationOption::ConfigurationOption

### ISSUE THREAD

**Issue by pengweichu** [mfontanini/cppkafka#85]
I've successfully compiled the cppkafka as guide: cmake -DRDKAFKA_ROOT_DIR=/home/test/rdkafka -DCPPKAFKA_BUILD_SHARED=OFF

But when I link it into my application,  I'm always got error as below, but I already linked to boost program options:
`find_package(Boost COMPONENTS program_options filesystem system)`

How can I fix this issue ?

> undefined reference to `cppkafka::ConfigurationOption::ConfigurationOption(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

**Comment by DSwift510** [comment]
I'm getting a similar issue attempting to build and run the example on Xcode

> Undefined symbols for architecture x86_64:
>  "cppkafka::Configuration::Configuration(std::initializer_list<cppkafka::ConfigurationOption> 
> const&)", referenced from:
>      _main in main.o
>  "cppkafka::ConfigurationOption::ConfigurationOption(std::__1::basic_string<char, 
> std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*)", referenced from:
>      _main in main.o
>  "cppkafka::Buffer::Buffer(std::__1::basic_string<char, std::__1::char_traits<char>, 
> std::__1::allocator<char> > const&)", referenced from:
>      _main in main.o
>  "cppkafka::Buffer::Buffer()", referenced from:
>      cppkafka::BasicMessageBuilder<cppkafka::Buffer, 
> cppkafka::MessageBuilder>::BasicMessageBuilder(std::__1::basic_string<char, 
> std::__1::char_traits<char>, std::__1::allocator<char> >) in main.o
>  "cppkafka::Producer::flush()", referenced from:
>      _main in main.o
>  "cppkafka::Producer::produce(cppkafka::MessageBuilder const&)", referenced from:
>      _main in main.o
>  "cppkafka::Producer::Producer(cppkafka::Configuration)", referenced from:
>      _main in main.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is this platform specific?

**Comment by DSwift510** [comment]
I made a second attempt on an Ubuntu 16.01 VM using Eclipse and got the following errors as well:

> makefile:44: recipe for target 'csharpkafka' failed
> ./ckafka.o: In function `main':
> /home/parallels/workspace/csharpkafka/Debug/../ckafka.cpp:10: undefined reference to 
> `cppkafka::ConfigurationOption::ConfigurationOption(std::__cxx11::basic_string<char, 
> std::char_traits<char>, std::allocator<char> > const&, char const*)'
> /home/parallels/workspace/csharpkafka/Debug/../ckafka.cpp:10: undefined reference to 
> `cppkafka::Configuration::Configuration(std::initializer_list<cppkafka::ConfigurationOption> const&)'
> /home/parallels/workspace/csharpkafka/Debug/../ckafka.cpp:13: undefined reference to 
> `cppkafka::Producer::Producer(cppkafka::Configuration)'
> /home/parallels/workspace/csharpkafka/Debug/../ckafka.cpp:18: undefined reference to 
> `cppkafka::Buffer::Buffer(std::__cxx11::basic_string<char, std::char_traits<char>, 
> std::allocator<char> > const&)'
> /home/parallels/workspace/csharpkafka/Debug/../ckafka.cpp:18: undefined reference to 
> `cppkafka::Producer::produce(cppkafka::MessageBuilder const&)'
> /home/parallels/workspace/csharpkafka/Debug/../ckafka.cpp:19: undefined reference to 
> `cppkafka::Producer::flush()'
> ./ckafka.o: In function `cppkafka::BasicMessageBuilder<cppkafka::Buffer, 
> cppkafka::MessageBuilder>::BasicMessageBuilder(std::__cxx11::basic_string<char, 
> std::char_traits<char>, std::allocator<char> >)':
> /usr/local/include/cppkafka/message_builder.h:192: undefined reference to 
> `cppkafka::Buffer::Buffer()'
> /usr/local/include/cppkafka/message_builder.h:192: undefined reference to 
> `cppkafka::Buffer::Buffer()'
> collect2: error: ld returned 1 exit status
> make: *** [csharpkafka] Error 1
 
Any help would be much appreciated!

**Comment by mfontanini** [comment]
Are you linking with `cppkafka`? This is probably an issue on your setup as this builds in travis after every commit and that's currently working fine.

**Comment by DSwift510** [comment]
It was definitely my setup. IDE was looking for the library in a strange place. Thank you for the help!
