### ISSUE TITLE
Examples binaries not being generated.

### ISSUE THREAD

**Issue by bpinaya** [mfontanini/cppkafka#9]
Hi there, I was checking your wrapper and wanted to test it out but after I build it the examples binaries are not being generated due to the: EXCLUDE_FROM_ALL option.
Any reason for that? Or am I doing the cmake wrong, because otherwise the binaries of the examples are not being generated.
Thanks for your time!

**Comment by mfontanini** [comment]
Examples are not built every time you build the library on purpose. If you
want to build them, just run `make examples`

**Comment by bpinaya** [comment]
Oh thanks!! Didn't knew about `make examples`
Sorry about that, I am still learning about Cmake

**Comment by Shielsy** [comment]
I've just been caught out by this. There is cmake option called _CPPKAFKA_DISABLE_EXAMPLES_ which is OFF by default, therefore I presumed that the tests would be built.

**Comment by krishnakumar3044** [comment]
I too thought that "examples" are built by default, as CPPKAFKA_DISABLE_EXAMPLES is "OFF" by default
