### ISSUE TITLE
MSVC name-mangling issue

### ISSUE THREAD

**Issue by dmpas** [mfontanini/cppkafka#97]
```
LNK2019	unresolved external symbol "public: class std::shared_ptr<struct cppkafka::Internal> __thiscall cppkafka::MessageInternal::get_internal(void)const "
(?get_internal@MessageInternal@cppkafka@@QBE?AV?$shared_ptr@UInternal@cppkafka@@@std@@XZ)
referenced in function "private: class cppkafka::Message & __thiscall cppkafka::Message::load_internal(void)"
 (?load_internal@Message@cppkafka@@AAEAAV12@XZ)	.....\cppkafka.lib(message.obj)	1	
```
MSVC trying to find `?get_internal@MessageInternal@cppkafka@@QBE?AV?$shared_ptr@UInternal@cppkafka@@@std@@XZ`
but in `message_internal.obj` it mangled in `?get_internal@MessageInternal@cppkafka@@QBE?AV?$shared_ptr@VInternal@cppkafka@@@std@@XZ`

The difference: `@UInternal@` vs `@VInternal@` - `struct` vs `class` (accorging to https://en.wikiversity.org/wiki/Visual_C%2B%2B_name_mangling and `undname` tool).

for private use `Internal` is declared as a class:
https://github.com/mfontanini/cppkafka/blob/master/include/cppkafka/message_internal.h#L39

for public use it is a struct:
https://github.com/mfontanini/cppkafka/blob/master/include/cppkafka/message.h#L46

I propose to change public declaration to class too. Can I make a pull request?

**Comment by mfontanini** [comment]
So there's 2 issues here:

* As you said, the forward declaration should be `class`.
* Also, the class `MessageInternal` should be defined using the `CPPKAFKA_API` macro (defined in `macros.h`), see the `Message` class definition for reference.

If you want to make a PR for this, that would be great! There's actually probably some other issues with not using `CPPKAFKA_API` in the rest of the classes some contributor added recently (I completely forgot to check that), e.g. you can find them by running `grep -R class include/  | grep -v ';' | grep -v CPPKAFKA_API`.

**Comment by dmpas** [comment]
I'm not sure that this private class `MessageInternal` should be marked as `CPPKAFKA_API`. This macro defines DLL export/import, but private class is not supposed to be exported/imported.
